# 2.1数据操作

## 2.1.1 入门

In [3]:
import torch

In [4]:
#张量表示由一个数值组成的数组，这个数组可能有多个维度。具有一个轴的张量对应数学上的向量(vector)，具有两个轴的张量对应数学上的矩阵（matrix）
#具有两个轴以上的张量没有特殊的数学名称

#使用arange创建一个行向量x,这个行向量包含以0开始的前12个整数，张量中的每个值都称为张量的元素（element）。
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
#可以通过张量的shape属性来访问张量（沿每个轴的长度）的形状
x.shape

torch.Size([12])

In [6]:
#如果只是想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小(size)。
x.numel()

12

In [7]:
#想要改变一个张量的形状而不改变元素数量和元素值，可以调用reshape函数
X = x.reshape(3, 4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [8]:
#不需要手动指定每个维度来改变形状，知道宽度后，高度会被自动计算得出。可以通过-1来调用自动计算维度的功能。
X2 = x.reshape(-1, 4)
X2

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [9]:
X3 = x.reshape(3, -1)
X3

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [10]:
#需要全0、全1或其他常量，或从特定分布中随机采样的数字来初始化矩阵。
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [12]:
#想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值。例如，当我们构造数组来作为神经网络中的参数时，我们通常会随机初始化参数的值。
#randn-其中每个元素都从均值为0，标准差为1的标准高斯分布（正态分布）中随机采样
torch.randn(3, 4)

tensor([[ 2.2926,  0.9057, -1.3107, -0.5029],
        [-0.1740,  0.7878,  0.0781,  1.2454],
        [-0.6124,  0.6080, -0.7399, -1.3405]])

In [13]:
#可以通过提供包含数值的python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值。
#最外层的列表对应于轴0，内层的列表对应于轴1
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

## 2.1.2 运算符

In [14]:
#对于具有任意形状的张量，常见的标准算数运算符（+、-、*、/和**）都可以被升级为按元素运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y # **是求幂运算符号

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [15]:
#按元素方式可以应用更多的计算，包括像求幂这样的一元运算符。
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [16]:
#也可以把多个张量连结在一起，把他们端对端地叠起来形成一个更大的张量。只需要提供张量列表，并给出沿哪个轴连结。
#下面的例子演示了当我们沿行（轴-0）和按列（轴-1）连结两个矩阵时会发生什么
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [17]:
#通过逻辑运算构建二维张量
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [18]:
#对张量中的所有元素进行求和，会产生一个单元素张量
X.sum()

tensor(66.)

## 2.1.3 广播机制

In [19]:
#在某些情况下，即使形状不同，我们仍然可以通过调用广播机制来执行按元素操作
#工作方式为：首先，通过适当复制元素来扩展一个或两个数组，以便在转换后两个张量具有相同的形状，其次，对生成的数组执行按元素操作

In [20]:
#大多数情况下，沿着数组中长度为1的轴进行广播
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [21]:
#如果让a和b形状相加，它们的形状不匹配，我们将两个矩阵广播为更大的3 * 2矩阵
#a复制列，b复制行
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 2.1.4 索引和切片

In [22]:
#张量中的元素可以通过索引访问，第一个元素的索引为0， 最后一个元素的索引为-1

#用[-1]选择最后一个元素，用[1:3]选择第二和第三个元素
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [23]:
#除读取外，还可以通过指定索引来将元素写入矩阵
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [24]:
#想为多个元素赋相同的值，只需要索引所有的元素，然后为他们赋值。例如，[0:2, :]访问第1行和第2行
#':'代表沿着轴1（列）的所有元素
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

## 2.1.5 节省内存

In [25]:
#运行一些操作可能会导致为新结果分配内存。例如用Y=X+Y，将取消引用Y指向的张量，而是指向新分配的内存处的张量。

In [26]:
#用python中的id()函数演示这一点，它提供了内存中引用对象的确切地址
before = id(Y)
Y = Y + X
id(Y) == before
#Y已指向内存中的新位置。
#这是不可取的，原因有二：首先，我们不想总是不必要地分配内存，在机器学习中我们可能有数百兆的参数
# 并且在一秒内多次更新所有参数，通常情况下希望在原地执行这些参数
#其次，如果原地不更新，其他引用仍然会指向旧的内存位置，这样某些代码可能会无意中引用旧的参数

False

In [27]:
#原地执行操作非常简单，可以使用切片表示法将操作的结果分配给先前分配的数组。
#zeros_like用来分配一个全0的块
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 2600113539328
id(Z): 2600113539328


In [29]:
#若后续的计算中没有重复使用X,则可以使用X[:] = X + Y或 X+=Y来减少操作的内存开销。
before = id(X)
X += Y
id(X) == before

True

## 2.1.6 转换为其他Python对象

In [30]:
#torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会同时更改另一个张量
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [31]:
#要将大小为1的张量转换为Python标量，我们可以调用item函数或者Python的内置函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 2.1.7 小结

In [ ]:
#深度学习存储和操作数据的主要接口是张量（n维数组）。
#它提供了各种功能，包括基本数学运算、广播、索引、切片、内存节省和转换其他Python对象